services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: osuacmoj
      POSTGRES_USER: spring
      POSTGRES_DB: problems
    labels:
      org.springframework.boot.service-connection: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 1420:8080